// <auto-generated />
namespace MvcPractice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BirthdaywasaddedtoCustomermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BirthdaywasaddedtoCustomermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201810281309370_Birthday was added to Customer model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
